//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinalLEC.ModelTypeManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelType
    {
        public int ModelTypeID { get; set; }
        public int BrandID { get; set; }
        public string ModelTypeName { get; set; }
        public string ModelTypeImage { get; set; }
        public int ModelTypePrice { get; set; }
        public int ModelTypeStock { get; set; }
        public string ModelTypeDescription { get; set; }
    }
}
